### ISSUE TITLE
在Windows终端上显示不是内部或外部命令，无法执行

### ISSUE THREAD

**Issue by puchaoyi** [kennethreitz/pip-pop#14]
![image](https://cloud.githubusercontent.com/assets/19931272/23068861/3eda94c8-f560-11e6-8b53-724f4e48d307.png)

**Comment by linxidd** [comment]
>python pip-diff.py .......没有安装当然不能直接使用了只能用这种形式运行,而且你要安装docopt库>pip install docopt，或者去根目录先运行>python setup.py install推荐第二种

**Comment by puchaoyi** [comment]
已经能运行了， docopt安装了，只是需要到Python下的scripts目录下才能运行
非常感谢！
祝好





在 2017-02-26 11:49:21，"linxidd" <notifications@github.com> 写道：


python pip-diff.py .......没有安装当然不能直接使用了只能用这种形式运行,而且你要安装docopt库>pip install docopt，或者去根目录先运行>python setup.py install推荐第二种
