### ISSUE TITLE
Question about pip-grep

### ISSUE THREAD

**Issue by lvhua6352** [kennethreitz/pip-pop#15]
If the parameters contain multiple packages, such as "pip-grep tests/test-requirements.txt requests django", and the "test-requirements.txt" include these two packages too. But the program only print the first package. Is it normal?
Thanks.

**Comment by sloooooooooow** [comment]
同问

**Comment by wangyunchuan2012** [comment]
'module' object has no attribute 'EX_NOINPUT', why?

**Comment by kennethreitz** [comment]
yes
