### ISSUE TITLE
Broken with recent versions of pip

### ISSUE THREAD

**Issue by pmclanahan** [kennethreitz/pip-pop#5]
pip changed the signature of `parse_requirements` to require a `session` keyword argument as of version 6. Should be able to pass in whatever session is required for forward and backward compat. I'll submit a PR when I get time if you've not gotten to it by then.

**Comment by sigmavirus24** [comment]
For what it's worth @kennethreitz, pip is not an API so anything you import from pip will not have a backwards compatibility guarantee. It's not a library provided but a CLI. Many people run into problems like this because people tend to think that if they can import it they can use it.

**Comment by kennethreitz** [comment]
@pmclanahan sessions have been in here for months :)

@sigmavirus24 very aware. doesn't matter.

**Comment by pmclanahan** [comment]
Doh! Sorry about that @kennethreitz. I failed to realize how long ago the version on PyPI was uploaded. Should have tried master before filing. Thanks!
